### PR TITLE
Added myself to the members page

### PR DESCRIPTION
**Pull request by regalcat**
## Problem/Feature
I'm not on the members page yet.
Issue [#51](https://github.com/ISU-WebDevClub/club-website/issues/51)

## Solution
I added myself to the members page.

## What to Test
- [ ] The picture shows up
- [ ] The description and name show up

## Reviewers
@KrashLeviathan 
FYI: @KrashLeviathan @csteamengine @CivBase

### CODE REVIEW

**Comment by KrashLeviathan** [comment]
You'll need to crop the image so it's a square. Otherwise it's stretching funny inside the member box. 

screen shot 2015-09-30 at 8 30 29 pm

Also, in #51 I mentioned having three image sizes for the members pictures: "-lg" (512x512 - 1024x1024), "-md" (256x256), and "-sm" (64x64). That sort of standardizes things and makes it easier down the road. Even if you don't add the other two sizes now, the 256x256 pic should be used for the members page so it's good quality but doesn't add too much to the load time.

**Comment by regalcat** [comment]
@KrashLeviathan Ok. I think it's ready to be merged now.

**Comment by KrashLeviathan** [comment]
One suggestion (sorry!) - use the medium picture for the members page instead of the large one. That'll save on load time as we get more members.

**Comment by regalcat** [comment]
@KrashLeviathan Changed it. And fixed my merge conflicts.

**Comment by KrashLeviathan** [comment]
+1

**Pull request merged**
