### PR TITLE
Member's Page Expansion - Robert Kloster

### PR DESCRIPTION
**Pull request by RobertKloster**
### Problem / Feature
Lack of an image for Robert Kloster on the member's page on the website.

### Solution
Inclusion of an image for Robert Kloster on the member's page on the website.  A blurb has also been included.

### What To Test
That the system does not explode.  Also for general quality.

### Reviewers
@KrashLeviathan @csteamengine @regalcat

### CODE REVIEW

**Comment by KrashLeviathan** [comment]
Merge conflicts. Pull WDC master into your local branch again, fix merge conflicts, and push it again. If you need help, reach out on Slack. I'm going to try to get something posted to help if you've never dealt with merge conflicts before. Other than that, everything looks good.

**Comment by RobertKloster** [comment]
Not certain if it worked, but I pulled down master from "Upstream", as it were, committed the change, and pushed it.  Let me know if there's anything else I should do.

**Comment by KrashLeviathan** [comment]
Looks like you still have merge conflicts. I'm actually in the middle of writing a how-to for dealing with merge conflicts, and I should have it up tonight. Basically, when you look at the members.json file you see there are three strange lines in there: `<<<<<<<<< HEAD`, `=======`, and `>>>>>>>> [gibberish]`. The stuff in between the `<<<<` and `>>>>` is the stuff in conflict. The `====` separates the two conflicting pieces of code. The stuff in the upper part is what's in your local branch (on your computer). The stuff in the lower part is what you're trying merged in. You need to make them both work together, and then remove the `<<<<`, `====`, and `>>>>` lines. So, in your case, you want to keep the "Robert Kloster" items and the "Robert Stemig" items, but discard the Nic Cage stuff. I hope that's not too confusing. If it is, wait until tomorrow and hopefully I'll have that how-to doc up for reference.

**Comment by RobertKloster** [comment]
Pushed it again. (Now with merge conflict resolution!)

**Comment by KrashLeviathan** [comment]
+1

**Pull request merged**
