### PR TITLE
First attempt adding name

### PR DESCRIPTION
**Pull request by Michielu**
First attempt, only text changed. Nothing can break.

### CODE REVIEW

**Comment by CivBase** [comment]
> Nothing can break.

You will learn soon enough.

**Comment by KrashLeviathan** [comment]
Lol. Looks good man but you gotta add a picture! A square one. 64x64. Check out Issue #51

**Comment by KrashLeviathan** [comment]
Whoops! I meant 256x256.

**Comment by KrashLeviathan** [comment]
+1

**Pull request merged**
