### PR TITLE
first design of members page

### PR DESCRIPTION
**Pull request by JackRometty**
### Problem / Feature
feature: new members page added. basic design with filler pictures & text.
screen shot 2015-09-19 at 5 09 28 pm

### Reviewers

@regalcat 

FYI: @KrashLeviathan @csteamengine @regalcat

### CODE REVIEW

**Comment by michaelrupert-wf** [comment]
Would you mind throwing a screenshot of the page in the PR?

**Comment by KrashLeviathan** [comment]
He left for the night.

**Comment by JackRometty** [comment]
i added a photo & fixed merge conflicts. is everything good?

**Comment by regalcat** [comment]
Looks good. So much Nicolas Cage...
+1

**Pull request merged**
