### PR TITLE
added a photo I guess

### PR DESCRIPTION
**Pull request by frostbyte100**
### Anyone

@KrashLeviathan

### CODE REVIEW

**Comment by KrashLeviathan** [comment]
Looks good, except it needs to be a square pic, otherwise it gets stretched.

screen shot 2015-10-01 at 8 57 59 am

I recommend finding a picture that you can crop and scale to 256x256 px so it's consistent size/quality with the rest of the member photos.

**Comment by frostbyte100** [comment]
My bad, will do

On Thu, Oct 1, 2015 at 8:59 AM, Nathan Karasch <notifications@github.com>
wrote:

> Looks good, except it needs to be a square pic, otherwise it gets
> stretched.
>
> [image: screen shot 2015-10-01 at 8 57 59 am]
> <https://cloud.githubusercontent.com/assets/8837587/10222616/9afd05c6-681a-11e5-84da-2e05603b3611.png>
>
> I recommend finding a picture that you can crop and scale to 256x256 px so
> it's consistent size/quality with the rest of the member photos.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ISU-WebDevClub/club-website/pull/59#issuecomment-144734225>
> .
>



-- 
Leelabari Fulbel

**Comment by frostbyte100** [comment]
My Picture

Added my picture

If it works

Anyone

@KrashLeviathan

**Comment by KrashLeviathan** [comment]
The photo is still getting stretched, and it's... sideways. Lol. Which is fine if that's what you're going for, but...

memberbox

**Comment by KrashLeviathan** [comment]
You'll also need to pull the club master into your branch because you have merge conflicts. I'll be putting up a how-to sometime tonight on dealing with merge conflicts, so that should help explain what to do with them.

**Comment by KrashLeviathan** [comment]
https://github.com/KrashLeviathan/club-website/blob/add_tutorials_folder_and_merge_conflicts/resources/tutorials/merge_conflicts.md

**Comment by frostbyte100** [comment]
Nathan, how would I pull the club master to my forked branch? I'm more used
to using github as a contributor to a branch.

On Sat, Oct 10, 2015 at 11:15 AM, Nathan Karasch <notifications@github.com>
wrote:

>
> https://github.com/KrashLeviathan/club-website/blob/add_tutorials_folder_and_merge_conflicts/resources/tutorials/merge_conflicts.md
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ISU-WebDevClub/club-website/pull/59#issuecomment-147103069>
> .
>



-- 
Leelabari Fulbel

**Comment by frostbyte100** [comment]
Also I am using the git bash not the software that creates a visual branch
for github.

On Sat, Oct 10, 2015 at 4:22 PM, Leelabari Fulbel <
fulbel.leelabari@gmail.com> wrote:

> Nathan, how would I pull the club master to my forked branch? I'm more
> used to using github as a contributor to a branch.
>
> On Sat, Oct 10, 2015 at 11:15 AM, Nathan Karasch <notifications@github.com
> > wrote:
>
>>
>> https://github.com/KrashLeviathan/club-website/blob/add_tutorials_folder_and_merge_conflicts/resources/tutorials/merge_conflicts.md
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ISU-WebDevClub/club-website/pull/59#issuecomment-147103069>
>> .
>>
>
>
>
> --
> Leelabari Fulbel
>



-- 
Leelabari Fulbel

**Comment by frostbyte100** [comment]
My Picture

Added my picture

If it works

Anyone

@KrashLeviathan

**Comment by frostbyte100** [comment]
Never mind, I have figured that out for myself.

On Sat, Oct 10, 2015 at 4:23 PM, Leelabari Fulbel <
fulbel.leelabari@gmail.com> wrote:

> Also I am using the git bash not the software that creates a visual branch
> for github.
>
> On Sat, Oct 10, 2015 at 4:22 PM, Leelabari Fulbel <
> fulbel.leelabari@gmail.com> wrote:
>
>> Nathan, how would I pull the club master to my forked branch? I'm more
>> used to using github as a contributor to a branch.
>>
>> On Sat, Oct 10, 2015 at 11:15 AM, Nathan Karasch <
>> notifications@github.com> wrote:
>>
>>>
>>> https://github.com/KrashLeviathan/club-website/blob/add_tutorials_folder_and_merge_conflicts/resources/tutorials/merge_conflicts.md
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/ISU-WebDevClub/club-website/pull/59#issuecomment-147103069>
>>> .
>>>
>>
>>
>>
>> --
>> Leelabari Fulbel
>>
>
>
>
> --
> Leelabari Fulbel
>



-- 
Leelabari Fulbel

**Comment by frostbyte100** [comment]
My Picture

Added my picture

If it works

Anyone

@KrashLeviathan

**Comment by KrashLeviathan** [comment]
+1
The Nic Cages got added back in, but we can remove them again later.

**Pull request merged**
